DESTDIR =
USRBINDIR = /usr/bin
BINDIR = /bin
MANDIR = /usr/share/man
LIBDIR = /usr/lib
ETCDIR = /etc

# TODO: Update this with each release
VERSION = '0.9.4'
NAME = pl_bash_functions

PKG_DIR = $(NAME)
DIRSCRIPTS = scripts
DIRTESTS = tests

# End of file

